const SummaryPreview = () => {
  return (
    <div className="rounded-2xl border border-slate-200 bg-white">
      <div className="border-b border-slate-100 px-6 py-4">
        <h3 className="font-semibold text-slate-900">
          AI Executive Summary
        </h3>

        <p className="mt-1 text-sm text-slate-500">
          Automatically generated from the uploaded report.
        </p>
      </div>

      <div className="space-y-4 px-6 py-6">
        <div className="flex items-start gap-3">
          <span>📈</span>
          <p>Revenue increased by <strong>12%</strong> year-over-year.</p>
        </div>

        <div className="flex items-start gap-3">
          <span>💰</span>
          <p>Net profit remained stable despite higher expenses.</p>
        </div>

        <div className="flex items-start gap-3">
          <span>💵</span>
          <p>Cash flow remained positive throughout the year.</p>
        </div>

        <div className="flex items-start gap-3">
          <span>⚠</span>
          <p>Debt ratio increased but remains within industry norms.</p>
        </div>
      </div>

      <div className="border-t border-slate-100 px-6 py-3 text-xs text-slate-400">
        Generated by FinSight AI
      </div>
    </div>
  );
};

export default SummaryPreview;